[package]
name = "tilt-ui-example-routing"
version = "0.0.0"
edition.workspace = true
publish = false

[[bin]]
name = "routing-showcase"
path = "src/main.rs"

[dependencies]
bevy = { workspace = true, features = [
    "bevy_core_pipeline", "bevy_ui_render", "bevy_winit", "default_font", "png", "wayland", "x11",
] }
tilt-ui.workspace = true
serde.workspace = true

[build-dependencies]
tilt-ui-build.workspace = true

[dev-dependencies]
tilt-ui-html.workspace = true
