//! Connects authored event bindings with Rust systems registered by macros.

use std::collections::{BTreeMap, HashMap};

use bevy::{
    app::{App, Plugin, Update},
    ecs::{
        entity::Entity,
        hierarchy::ChildOf,
        message::{Message, MessageCursor, MessageReader, MessageWriter, Messages},
        observer::On,
        query::{Added, Changed},
        system::{In, Query, SystemId},
        world::World,
    },
    input::{ButtonState, keyboard::KeyboardInput},
    prelude::{DetectChanges, IntoScheduleConfigs},
    ui::{ScrollPosition, widget::TextScroll},
};
use bevy_input_focus::{FocusGained, FocusLost, InputFocus};
use bevy_picking::{
    events::{
        Drag, DragEnd, DragStart, Enter, Leave, Move, Out, Over, Pointer, Press, Release, Scroll,
    },
    pointer::PointerId,
};

use crate::{
    ColorPickerChanged, ControlActivated, ControlCheckedChanged, EditableTextChanged,
    FormSubmitted, OptionSelectionChanged, SliderChanged,
};

use super::{
    EventBindings, StaticAttributes, TiltElement,
    inline_actions::{EventCall, execute_mutation, parse_script},
};

/// A template event delivered to a Rust `#[html_fn]` handler.
///
/// Templates can bind `onkeydown="handle_key"` or `(keydown)="handle_key()"`.
/// Pointer events expose `x`/`y` and optional `delta_x`/`delta_y`, drag
/// events additionally expose `distance_x`/`distance_y`, keyboard events
/// expose `key_code`/`key`/`text`/`repeat`, and scroll events expose `x`/`y`.
#[derive(Message, Debug, Clone, PartialEq, Eq)]
pub struct HtmlEvent {
    /// Entity on which the event originated.
    pub target: Entity,
    /// Normalized event name, such as `click` or `change`.
    pub kind: &'static str,
    /// Current value for editable and checkable controls, when applicable.
    pub value: Option<String>,
    /// Submit button for a form submission.
    pub submitter: Option<Entity>,
    /// Named event data (form fields, pointer coordinates, key details, or scroll position).
    pub data: BTreeMap<String, String>,
    /// Name of the registered Rust handler.
    pub handler: String,
}

/// Typed click payload accepted by `#[html_fn]`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct HtmlClick {
    pub target: Entity,
}

impl TryFrom<HtmlEvent> for HtmlClick {
    type Error = ();
    fn try_from(event: HtmlEvent) -> Result<Self, Self::Error> {
        (event.kind == "click")
            .then_some(Self {
                target: event.target,
            })
            .ok_or(())
    }
}

/// Typed value-change payload accepted by `#[html_fn]`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HtmlChange {
    pub target: Entity,
    pub value: Option<String>,
}

impl TryFrom<HtmlEvent> for HtmlChange {
    type Error = ();
    fn try_from(event: HtmlEvent) -> Result<Self, Self::Error> {
        (event.kind == "change")
            .then_some(Self {
                target: event.target,
                value: event.value,
            })
            .ok_or(())
    }
}

/// Typed form-submit payload accepted by `#[html_fn]`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HtmlSubmit {
    pub target: Entity,
    pub submitter: Entity,
    pub data: BTreeMap<String, String>,
}

impl TryFrom<HtmlEvent> for HtmlSubmit {
    type Error = ();
    fn try_from(event: HtmlEvent) -> Result<Self, Self::Error> {
        if event.kind != "submit" {
            return Err(());
        }
        Ok(Self {
            target: event.target,
            submitter: event.submitter.ok_or(())?,
            data: event.data,
        })
    }
}

/// Rust startup-system registration generated by `#[component_init]`.
pub struct ComponentInitRegistration {
    /// Adds the system to the application.
    pub register: fn(&mut App),
}

inventory::collect!(ComponentInitRegistration);

/// Rust update-system registration generated by `#[component_update]`.
pub struct ComponentUpdateRegistration {
    /// Adds the system to the application.
    pub register: fn(&mut App),
}

inventory::collect!(ComponentUpdateRegistration);

/// Rust event-handler registration generated by `#[html_fn]`.
pub struct HtmlHandlerRegistration {
    /// Name used in template event bindings.
    pub name: &'static str,
    /// Registers the handler as a Bevy system.
    pub register: fn(&mut World) -> SystemId<In<HtmlEvent>, ()>,
}

inventory::collect!(HtmlHandlerRegistration);

/// Installs Rust component startup systems and template event handlers.
#[derive(Debug, Default, Clone, Copy)]
pub struct TiltUiCodePlugin;

impl Plugin for TiltUiCodePlugin {
    fn build(&self, app: &mut App) {
        install(app);
    }
}

#[derive(bevy::ecs::resource::Resource, Default)]
struct HandlerSystems(HashMap<&'static str, SystemId<In<HtmlEvent>, ()>>);

#[derive(bevy::ecs::resource::Resource, Default)]
struct HandlerCursor(MessageCursor<HtmlEvent>);

#[derive(bevy::ecs::resource::Resource, Default)]
struct InlineActionCache(HashMap<String, Result<Vec<EventCall>, String>>);

pub(super) fn install(app: &mut App) {
    super::binding::install(app);
    super::method::install(app);
    for registration in inventory::iter::<ComponentInitRegistration> {
        (registration.register)(app);
    }
    for registration in inventory::iter::<ComponentUpdateRegistration> {
        (registration.register)(app);
    }
    // The code plugin is also usable on its own in minimal Bevy apps.
    // Register every input stream that its forwarders read.
    app.add_message::<KeyboardInput>()
        .add_message::<Pointer<Over>>()
        .add_message::<Pointer<Out>>()
        .add_message::<Pointer<Enter>>()
        .add_message::<Pointer<Leave>>()
        .add_message::<Pointer<Press>>()
        .add_message::<Pointer<Release>>()
        .add_message::<Pointer<Move>>()
        .add_message::<Pointer<DragStart>>()
        .add_message::<Pointer<Drag>>()
        .add_message::<Pointer<DragEnd>>()
        .add_message::<Pointer<Scroll>>()
        .add_message::<HtmlEvent>()
        .add_message::<FormSubmitted>()
        .add_message::<ControlActivated>()
        .add_message::<ControlCheckedChanged>()
        .add_message::<EditableTextChanged>()
        .add_message::<SliderChanged>()
        .add_message::<OptionSelectionChanged>()
        .add_message::<ColorPickerChanged>()
        .init_resource::<InputFocus>()
        .init_resource::<HandlerCursor>()
        .init_resource::<InlineActionCache>()
        .add_observer(forward_focus_gained)
        .add_observer(forward_focus_lost)
        .add_systems(
            Update,
            (
                super::binding::refresh_shared_values,
                super::flow::update_flow,
                super::binding_runtime::apply_bindings,
            )
                .chain()
                .after(super::TiltUiComponentRuntimeSet::Instantiate),
        )
        .add_systems(
            Update,
            (
                forward_activations,
                forward_checked,
                forward_edited,
                forward_slider_changed,
                forward_option_changed,
                forward_color_changed,
            )
                .after(crate::control::TiltControlSystems::Selection),
        )
        .add_systems(
            Update,
            forward_submissions.after(crate::widgets::structure::form::process_form_activation),
        )
        .add_systems(
            Update,
            (
                forward_initialization,
                forward_keyboard,
                forward_scroll_position,
                forward_text_scroll,
                forward_over,
                forward_out,
                forward_enter,
                forward_leave,
            )
                .after(super::TiltUiComponentRuntimeSet::Instantiate)
                .before(dispatch_html_events),
        )
        .add_systems(
            Update,
            (
                forward_press,
                forward_release,
                forward_move,
                forward_drag_start,
                forward_drag,
                forward_drag_end,
                forward_wheel,
            )
                .before(dispatch_html_events),
        )
        .add_systems(
            Update,
            dispatch_html_events
                .after(forward_activations)
                .after(forward_checked)
                .after(forward_edited)
                .after(forward_slider_changed)
                .after(forward_option_changed)
                .after(forward_color_changed)
                .after(forward_submissions),
        );

    let mut systems = HandlerSystems::default();
    for registration in inventory::iter::<HtmlHandlerRegistration> {
        systems
            .0
            .insert(registration.name, (registration.register)(app.world_mut()));
    }
    app.insert_resource(systems);
}

type HandlerQuery<'w, 's> = Query<
    'w,
    's,
    (
        Option<&'static StaticAttributes>,
        Option<&'static EventBindings>,
        Option<&'static ChildOf>,
    ),
>;

fn emit_bound(
    target: Entity,
    kind: &'static str,
    data: BTreeMap<String, String>,
    elements: &HandlerQuery,
    events: &mut MessageWriter<HtmlEvent>,
) {
    let mut current = Some(target);
    while let Some(entity) = current {
        let Ok((attributes, bindings, parent)) = elements.get(entity) else {
            break;
        };
        if let Some(handler) = handler_for(kind, attributes, bindings).or_else(|| {
            (kind == "focus")
                .then(|| handler_for("foucs", attributes, bindings))
                .flatten()
        }) {
            events.write(HtmlEvent {
                target,
                kind,
                value: None,
                submitter: None,
                data,
                handler,
            });
            break;
        }
        // Bevy already emits separate enter/leave messages for ancestors.
        if matches!(kind, "mouseenter" | "mouseleave") {
            break;
        }
        current = parent.map(ChildOf::parent);
    }
}

fn has_bound_handler(target: Entity, kind: &str, elements: &HandlerQuery) -> bool {
    let mut current = Some(target);
    while let Some(entity) = current {
        let Ok((attributes, bindings, parent)) = elements.get(entity) else {
            break;
        };
        if handler_for(kind, attributes, bindings).is_some() {
            return true;
        }
        if matches!(kind, "mouseenter" | "mouseleave") {
            break;
        }
        current = parent.map(ChildOf::parent);
    }
    false
}

fn pointer_alias(kind: &str, pointer_id: PointerId) -> Option<&'static str> {
    match (kind, pointer_id) {
        ("mousedown", PointerId::Touch(_)) => Some("touchstart"),
        ("mouseup", PointerId::Touch(_)) => Some("touchend"),
        ("mousemove", PointerId::Touch(_)) => Some("touchmove"),
        ("dragend", _) => Some("dragstop"),
        _ => None,
    }
}

fn forward_initialization(
    elements: Query<Entity, Added<TiltElement>>,
    handlers: HandlerQuery,
    mut events: MessageWriter<HtmlEvent>,
) {
    for entity in &elements {
        // Initialization belongs to the authored element, not an ancestor.
        if let Ok((attributes, bindings, _)) = handlers.get(entity) {
            if let Some(handler) = handler_for("init", attributes, bindings) {
                events.write(HtmlEvent {
                    target: entity,
                    kind: "init",
                    value: None,
                    submitter: None,
                    data: BTreeMap::new(),
                    handler,
                });
            }
        }
    }
}

fn forward_focus_gained(
    focus: On<FocusGained>,
    handlers: HandlerQuery,
    mut events: MessageWriter<HtmlEvent>,
) {
    if focus.entity != focus.original_event_target() {
        return;
    }
    emit_bound(
        focus.entity,
        "focus",
        BTreeMap::new(),
        &handlers,
        &mut events,
    );
}

fn forward_focus_lost(
    focus: On<FocusLost>,
    handlers: HandlerQuery,
    mut events: MessageWriter<HtmlEvent>,
) {
    if focus.entity != focus.original_event_target() {
        return;
    }
    emit_bound(
        focus.entity,
        "blur",
        BTreeMap::new(),
        &handlers,
        &mut events,
    );
}

fn forward_keyboard(
    mut source: MessageReader<KeyboardInput>,
    focus: bevy::ecs::system::Res<InputFocus>,
    handlers: HandlerQuery,
    mut events: MessageWriter<HtmlEvent>,
) {
    let Some(target) = focus.get() else { return };
    for key in source.read() {
        let kind = if key.state == ButtonState::Pressed {
            "keydown"
        } else {
            "keyup"
        };
        if !has_bound_handler(target, kind, &handlers) {
            continue;
        }
        let mut data = BTreeMap::new();
        data.insert("key_code".into(), format!("{:?}", key.key_code));
        data.insert("key".into(), format!("{:?}", key.logical_key));
        data.insert("repeat".into(), key.repeat.to_string());
        if let Some(text) = &key.text {
            data.insert("text".into(), text.to_string());
        }
        emit_bound(target, kind, data, &handlers, &mut events);
    }
}

fn forward_scroll_position(
    positions: Query<
        (Entity, bevy::ecs::change_detection::Ref<ScrollPosition>),
        Changed<ScrollPosition>,
    >,
    handlers: HandlerQuery,
    mut events: MessageWriter<HtmlEvent>,
) {
    for (entity, position) in &positions {
        if !position.is_added() {
            let mut data = BTreeMap::new();
            data.insert("x".into(), position.0.x.to_string());
            data.insert("y".into(), position.0.y.to_string());
            emit_bound(entity, "scroll", data, &handlers, &mut events);
        }
    }
}

fn forward_text_scroll(
    positions: Query<(Entity, bevy::ecs::change_detection::Ref<TextScroll>), Changed<TextScroll>>,
    handlers: HandlerQuery,
    mut events: MessageWriter<HtmlEvent>,
) {
    for (entity, position) in &positions {
        if !position.is_added() {
            let mut data = BTreeMap::new();
            data.insert("x".into(), position.0.x.to_string());
            data.insert("y".into(), position.0.y.to_string());
            emit_bound(entity, "scroll", data, &handlers, &mut events);
        }
    }
}

macro_rules! pointer_forwarder {
    ($name:ident, $event:ty, $kind:literal, $pointer:ident, $data:ident, $handlers:ident, $events:ident, $extra:block) => {
        fn $name(
            mut source: MessageReader<Pointer<$event>>,
            $handlers: HandlerQuery,
            mut $events: MessageWriter<HtmlEvent>,
        ) {
            for $pointer in source.read() {
                if !has_bound_handler($pointer.entity, $kind, &$handlers)
                    && pointer_alias($kind, $pointer.pointer_id)
                        .is_none_or(|alias| !has_bound_handler($pointer.entity, alias, &$handlers))
                {
                    continue;
                }
                let mut $data = BTreeMap::new();
                $data.insert("x".into(), $pointer.pointer_location.position.x.to_string());
                $data.insert("y".into(), $pointer.pointer_location.position.y.to_string());
                $extra
                emit_bound($pointer.entity, $kind, $data, &$handlers, &mut $events);
            }
        }
    };
}

pointer_forwarder!(
    forward_over,
    Over,
    "mouseover",
    pointer,
    data,
    handlers,
    events,
    {}
);
pointer_forwarder!(
    forward_out,
    Out,
    "mouseout",
    pointer,
    data,
    handlers,
    events,
    {}
);
pointer_forwarder!(
    forward_enter,
    Enter,
    "mouseenter",
    pointer,
    data,
    handlers,
    events,
    {}
);
pointer_forwarder!(
    forward_leave,
    Leave,
    "mouseleave",
    pointer,
    data,
    handlers,
    events,
    {}
);
pointer_forwarder!(
    forward_press,
    Press,
    "mousedown",
    pointer,
    data,
    handlers,
    events,
    {
        data.insert("button".into(), format!("{:?}", pointer.event.button));
        if matches!(pointer.pointer_id, PointerId::Touch(_)) {
            emit_bound(
                pointer.entity,
                "touchstart",
                data.clone(),
                &handlers,
                &mut events,
            );
        }
    }
);
pointer_forwarder!(
    forward_release,
    Release,
    "mouseup",
    pointer,
    data,
    handlers,
    events,
    {
        data.insert("button".into(), format!("{:?}", pointer.event.button));
        if matches!(pointer.pointer_id, PointerId::Touch(_)) {
            emit_bound(
                pointer.entity,
                "touchend",
                data.clone(),
                &handlers,
                &mut events,
            );
        }
    }
);
pointer_forwarder!(
    forward_move,
    Move,
    "mousemove",
    pointer,
    data,
    handlers,
    events,
    {
        data.insert("delta_x".into(), pointer.event.delta.x.to_string());
        data.insert("delta_y".into(), pointer.event.delta.y.to_string());
        if matches!(pointer.pointer_id, PointerId::Touch(_)) {
            emit_bound(
                pointer.entity,
                "touchmove",
                data.clone(),
                &handlers,
                &mut events,
            );
        }
    }
);
pointer_forwarder!(
    forward_drag_start,
    DragStart,
    "dragstart",
    pointer,
    data,
    handlers,
    events,
    {
        data.insert("button".into(), format!("{:?}", pointer.event.button));
    }
);
pointer_forwarder!(
    forward_drag,
    Drag,
    "drag",
    pointer,
    data,
    handlers,
    events,
    {
        data.insert("button".into(), format!("{:?}", pointer.event.button));
        data.insert("delta_x".into(), pointer.event.delta.x.to_string());
        data.insert("delta_y".into(), pointer.event.delta.y.to_string());
        data.insert("distance_x".into(), pointer.event.distance.x.to_string());
        data.insert("distance_y".into(), pointer.event.distance.y.to_string());
    }
);
pointer_forwarder!(
    forward_drag_end,
    DragEnd,
    "dragend",
    pointer,
    data,
    handlers,
    events,
    {
        data.insert("button".into(), format!("{:?}", pointer.event.button));
        data.insert("distance_x".into(), pointer.event.distance.x.to_string());
        data.insert("distance_y".into(), pointer.event.distance.y.to_string());
        emit_bound(
            pointer.entity,
            "dragstop",
            data.clone(),
            &handlers,
            &mut events,
        );
    }
);
pointer_forwarder!(
    forward_wheel,
    Scroll,
    "wheel",
    pointer,
    data,
    handlers,
    events,
    {
        data.insert("delta_x".into(), pointer.event.x.to_string());
        data.insert("delta_y".into(), pointer.event.y.to_string());
        data.insert("unit".into(), format!("{:?}", pointer.event.unit));
    }
);

fn handler_for(
    event: &str,
    static_attributes: Option<&StaticAttributes>,
    bindings: Option<&EventBindings>,
) -> Option<String> {
    let handler = bindings
        .and_then(|bindings| {
            bindings
                .bindings
                .iter()
                .find(|binding| {
                    binding.name == event || binding.name.strip_prefix("on") == Some(event)
                })
                .map(|binding| binding.expression.clone())
        })
        .or_else(|| {
            static_attributes.and_then(|attributes| {
                attributes
                    .attributes
                    .iter()
                    .find(|attribute| attribute.name.strip_prefix("on") == Some(event))
                    .map(|attribute| attribute.value.clone())
            })
        });
    handler
        .map(|handler| {
            let handler = handler.trim();
            if handler.starts_with('$') || handler.contains(';') {
                handler.to_owned()
            } else {
                handler
                    .strip_suffix("()")
                    .unwrap_or(handler)
                    .trim()
                    .to_owned()
            }
        })
        .filter(|handler| !handler.is_empty())
}

fn forward_activations(
    mut source: MessageReader<ControlActivated>,
    elements: bevy::ecs::system::Query<(Option<&StaticAttributes>, Option<&EventBindings>)>,
    mut events: MessageWriter<HtmlEvent>,
) {
    for activation in source.read() {
        let Ok((attributes, bindings)) = elements.get(activation.entity) else {
            continue;
        };
        if let Some(handler) = handler_for("click", attributes, bindings) {
            events.write(HtmlEvent {
                target: activation.entity,
                kind: "click",
                value: None,
                submitter: None,
                data: BTreeMap::new(),
                handler,
            });
        }
    }
}

fn forward_checked(
    mut source: MessageReader<ControlCheckedChanged>,
    elements: bevy::ecs::system::Query<(Option<&StaticAttributes>, Option<&EventBindings>)>,
    mut events: MessageWriter<HtmlEvent>,
) {
    for change in source.read() {
        let Ok((attributes, bindings)) = elements.get(change.entity) else {
            continue;
        };
        if let Some(handler) = handler_for("change", attributes, bindings) {
            let mut data = BTreeMap::new();
            data.insert("checked".into(), change.checked.to_string());
            data.insert("selected".into(), change.checked.to_string());
            data.insert("value_type".into(), "boolean".into());
            events.write(HtmlEvent {
                target: change.entity,
                kind: "change",
                value: Some(change.checked.to_string()),
                submitter: None,
                data,
                handler,
            });
        }
    }
}

fn forward_edited(
    mut source: MessageReader<EditableTextChanged>,
    elements: bevy::ecs::system::Query<(Option<&StaticAttributes>, Option<&EventBindings>)>,
    mut events: MessageWriter<HtmlEvent>,
) {
    for change in source.read() {
        let Ok((attributes, bindings)) = elements.get(change.entity) else {
            continue;
        };
        if let Some(handler) = handler_for("change", attributes, bindings) {
            events.write(HtmlEvent {
                target: change.entity,
                kind: "change",
                value: Some(change.value.clone()),
                submitter: None,
                data: BTreeMap::new(),
                handler,
            });
        }
    }
}

fn forward_slider_changed(
    mut source: MessageReader<SliderChanged>,
    elements: Query<(Option<&StaticAttributes>, Option<&EventBindings>)>,
    mut events: MessageWriter<HtmlEvent>,
) {
    for change in source.read() {
        let Ok((attributes, bindings)) = elements.get(change.entity) else {
            continue;
        };
        if let Some(handler) = handler_for("change", attributes, bindings) {
            let mut data = BTreeMap::new();
            data.insert("value_type".into(), "number".into());
            if let Some(upper) = change.upper {
                data.insert("upper".into(), upper.to_string());
            }
            events.write(HtmlEvent {
                target: change.entity,
                kind: "change",
                value: Some(change.value.to_string()),
                submitter: None,
                data,
                handler,
            });
        }
    }
}

fn forward_option_changed(
    mut source: MessageReader<OptionSelectionChanged>,
    elements: Query<(Option<&StaticAttributes>, Option<&EventBindings>)>,
    mut events: MessageWriter<HtmlEvent>,
) {
    for change in source.read() {
        let Ok((attributes, bindings)) = elements.get(change.control) else {
            continue;
        };
        if let Some(handler) = handler_for("change", attributes, bindings) {
            let mut data = BTreeMap::new();
            data.insert("selected".into(), change.selected.to_string());
            data.insert("text".into(), change.value.clone());
            events.write(HtmlEvent {
                target: change.control,
                kind: "change",
                value: Some(change.value.clone()),
                submitter: None,
                data,
                handler,
            });
        }
    }
}

fn forward_color_changed(
    mut source: MessageReader<ColorPickerChanged>,
    elements: Query<(Option<&StaticAttributes>, Option<&EventBindings>)>,
    mut events: MessageWriter<HtmlEvent>,
) {
    for change in source.read() {
        let Ok((attributes, bindings)) = elements.get(change.entity) else {
            continue;
        };
        if let Some(handler) = handler_for("change", attributes, bindings) {
            let color = change.value;
            let channel = |value: f32| (value.clamp(0.0, 1.0) * 255.0).round() as u8;
            let (red, green, blue) = (
                channel(color.red),
                channel(color.green),
                channel(color.blue),
            );
            let hex = format!("#{red:02X}{green:02X}{blue:02X}");
            let mut data = BTreeMap::new();
            data.insert("hex".into(), hex.clone());
            data.insert("rgb".into(), format!("rgb({red}, {green}, {blue})"));
            data.insert(
                "rgba".into(),
                format!("rgba({red}, {green}, {blue}, {:.3})", color.alpha),
            );
            data.insert("red".into(), red.to_string());
            data.insert("green".into(), green.to_string());
            data.insert("blue".into(), blue.to_string());
            data.insert("alpha".into(), channel(color.alpha).to_string());
            events.write(HtmlEvent {
                target: change.entity,
                kind: "change",
                value: Some(hex),
                submitter: None,
                data,
                handler,
            });
        }
    }
}

fn forward_submissions(
    mut source: MessageReader<FormSubmitted>,
    elements: bevy::ecs::system::Query<(Option<&StaticAttributes>, Option<&EventBindings>)>,
    mut events: MessageWriter<HtmlEvent>,
) {
    for submission in source.read() {
        let Ok((attributes, bindings)) = elements.get(submission.form) else {
            continue;
        };
        let handler =
            handler_for("submit", attributes, bindings).or_else(|| submission.action.clone());
        if let Some(handler) = handler {
            events.write(HtmlEvent {
                target: submission.form,
                kind: "submit",
                value: None,
                submitter: Some(submission.submitter),
                data: submission.data.clone(),
                handler,
            });
        }
    }
}

fn dispatch_html_events(world: &mut World) {
    let events = world.resource_scope(
        |world, mut cursor: bevy::ecs::change_detection::Mut<HandlerCursor>| {
            cursor
                .0
                .read(world.resource::<Messages<HtmlEvent>>())
                .cloned()
                .collect::<Vec<_>>()
        },
    );
    for event in events {
        let script =
            if let Some(script) = world.resource::<InlineActionCache>().0.get(&event.handler) {
                script.clone()
            } else {
                let script = parse_script(&event.handler);
                let mut cache = world.resource_mut::<InlineActionCache>();
                if cache.0.len() >= 256 {
                    cache.0.clear();
                }
                cache.0.insert(event.handler.clone(), script.clone());
                script
            };
        let Ok(script) = script else {
            bevy::log::warn!(
                "Invalid HTML event script '{}': {}",
                event.handler,
                script.unwrap_err()
            );
            continue;
        };
        for call in script {
            match call {
                EventCall::Handler(name) => {
                    let system = world
                        .resource::<HandlerSystems>()
                        .0
                        .get(name.as_str())
                        .copied();
                    if let Some(system) = system {
                        let mut forwarded = event.clone();
                        forwarded.handler = name;
                        let _ = world.run_system_with(system, forwarded);
                    }
                }
                call @ EventCall::Mutation { .. } => {
                    if let Err(error) = execute_mutation(world, &event, &call) {
                        bevy::log::warn!("HTML inline action: {error}");
                    }
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use bevy::{
        camera::NormalizedRenderTarget,
        input::keyboard::{Key, KeyCode},
        math::Vec2,
    };
    use bevy_input_focus::FocusCause;
    use bevy_picking::{
        events::Drag,
        pointer::{Location, PointerButton},
    };

    fn attributes(name: &str, handler: &str) -> StaticAttributes {
        StaticAttributes {
            attributes: vec![super::super::StaticAttribute {
                name: name.into(),
                value: handler.into(),
            }],
        }
    }

    #[test]
    fn keyboard_events_use_the_focused_element_and_include_key_data() {
        let mut app = App::new();
        app.add_message::<KeyboardInput>()
            .add_message::<HtmlEvent>()
            .add_systems(Update, forward_keyboard);
        let target = app
            .world_mut()
            .spawn(attributes("onkeydown", "handle_key()"))
            .id();
        app.insert_resource(InputFocus::from_entity(target));
        app.world_mut()
            .resource_mut::<Messages<KeyboardInput>>()
            .write(KeyboardInput {
                key_code: KeyCode::KeyA,
                logical_key: Key::Character("a".into()),
                state: ButtonState::Pressed,
                text: Some("a".into()),
                repeat: false,
                window: target,
            });
        app.update();
        let events: Vec<_> = app
            .world_mut()
            .resource_mut::<Messages<HtmlEvent>>()
            .drain()
            .collect();
        assert_eq!(events.len(), 1);
        assert_eq!(events[0].kind, "keydown");
        assert_eq!(events[0].target, target);
        assert_eq!(events[0].handler, "handle_key");
        assert_eq!(events[0].data.get("text").map(String::as_str), Some("a"));
    }

    #[test]
    fn focus_observer_routes_to_bound_parent() {
        let mut app = App::new();
        app.add_message::<HtmlEvent>()
            .add_observer(forward_focus_gained);
        let parent = app
            .world_mut()
            .spawn(attributes("onfocus", "on_focus"))
            .id();
        let child = app.world_mut().spawn_empty().id();
        app.world_mut().entity_mut(parent).add_child(child);
        app.world_mut().trigger(FocusGained {
            entity: child,
            cause: FocusCause::Navigated,
        });
        let events: Vec<_> = app
            .world_mut()
            .resource_mut::<Messages<HtmlEvent>>()
            .drain()
            .collect();
        assert_eq!(events.len(), 1);
        assert_eq!(events[0].target, child);
        assert_eq!(events[0].kind, "focus");
    }

    #[test]
    fn drag_and_real_scroll_position_forward_payloads() {
        let mut app = App::new();
        app.add_message::<Pointer<Drag>>()
            .add_message::<HtmlEvent>()
            .add_systems(Update, (forward_drag, forward_scroll_position));
        let target = app
            .world_mut()
            .spawn((
                StaticAttributes {
                    attributes: vec![
                        super::super::StaticAttribute {
                            name: "ondrag".into(),
                            value: "on_drag".into(),
                        },
                        super::super::StaticAttribute {
                            name: "onscroll".into(),
                            value: "on_scroll".into(),
                        },
                    ],
                },
                ScrollPosition(Vec2::ZERO),
            ))
            .id();
        app.update();
        app.world_mut()
            .get_mut::<ScrollPosition>(target)
            .unwrap()
            .0
            .y = 28.0;
        app.world_mut()
            .resource_mut::<Messages<Pointer<Drag>>>()
            .write(Pointer::new(
                PointerId::Mouse,
                Location {
                    target: NormalizedRenderTarget::None {
                        width: 100,
                        height: 100,
                    },
                    position: Vec2::new(12.0, 16.0),
                },
                Drag {
                    button: PointerButton::Primary,
                    distance: Vec2::new(0.0, 8.0),
                    delta: Vec2::new(0.0, 3.0),
                },
                target,
            ));
        app.update();
        let events: Vec<_> = app
            .world_mut()
            .resource_mut::<Messages<HtmlEvent>>()
            .drain()
            .collect();
        assert_eq!(events.len(), 2);
        assert_eq!(
            events
                .iter()
                .find(|event| event.kind == "drag")
                .unwrap()
                .data["distance_y"],
            "8"
        );
        assert_eq!(
            events
                .iter()
                .find(|event| event.kind == "scroll")
                .unwrap()
                .data["y"],
            "28"
        );
    }

    #[test]
    fn event_binding_syntax_and_init_fire_once() {
        let bindings = EventBindings {
            bindings: vec![super::super::EventBinding {
                name: "mouseover".into(),
                expression: "on_hover()".into(),
            }],
        };
        assert_eq!(
            handler_for("mouseover", None, Some(&bindings)).as_deref(),
            Some("on_hover")
        );

        let mut app = App::new();
        app.add_message::<HtmlEvent>()
            .add_systems(Update, forward_initialization);
        let entity = app
            .world_mut()
            .spawn((
                TiltElement {
                    kind: tilt_ui_core::ElementKind::Div,
                },
                attributes("oninit", "on_init"),
            ))
            .id();
        app.update();
        let first: Vec<_> = app
            .world_mut()
            .resource_mut::<Messages<HtmlEvent>>()
            .drain()
            .collect();
        assert_eq!(first.len(), 1);
        assert_eq!(first[0].target, entity);
        assert_eq!(first[0].kind, "init");
        app.update();
        assert_eq!(
            app.world_mut()
                .resource_mut::<Messages<HtmlEvent>>()
                .drain()
                .count(),
            0
        );
    }
}
