//! Connects authored event bindings with Rust systems registered by macros.

use std::collections::{BTreeMap, HashMap};

use bevy::{
    app::{App, Plugin, Update},
    ecs::{
        entity::Entity,
        message::{Message, MessageCursor, MessageReader, MessageWriter, Messages},
        system::{In, SystemId},
        world::World,
    },
    prelude::IntoScheduleConfigs,
};

use crate::{ControlActivated, ControlCheckedChanged, EditableTextChanged, FormSubmitted};

use super::{EventBindings, StaticAttributes};

/// A template event delivered to a Rust `#[html_fn]` handler.
#[derive(Message, Debug, Clone, PartialEq, Eq)]
pub struct HtmlEvent {
    /// Entity on which the event originated.
    pub target: Entity,
    /// Normalized event name, such as `click` or `change`.
    pub kind: &'static str,
    /// Current value for editable and checkable controls, when applicable.
    pub value: Option<String>,
    /// Submit button for a form submission.
    pub submitter: Option<Entity>,
    /// Named values collected from a submitted form.
    pub data: BTreeMap<String, String>,
    /// Name of the registered Rust handler.
    pub handler: String,
}

/// Typed click payload accepted by `#[html_fn]`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct HtmlClick {
    pub target: Entity,
}

impl TryFrom<HtmlEvent> for HtmlClick {
    type Error = ();
    fn try_from(event: HtmlEvent) -> Result<Self, Self::Error> {
        (event.kind == "click")
            .then_some(Self {
                target: event.target,
            })
            .ok_or(())
    }
}

/// Typed value-change payload accepted by `#[html_fn]`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HtmlChange {
    pub target: Entity,
    pub value: Option<String>,
}

impl TryFrom<HtmlEvent> for HtmlChange {
    type Error = ();
    fn try_from(event: HtmlEvent) -> Result<Self, Self::Error> {
        (event.kind == "change")
            .then_some(Self {
                target: event.target,
                value: event.value,
            })
            .ok_or(())
    }
}

/// Typed form-submit payload accepted by `#[html_fn]`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HtmlSubmit {
    pub target: Entity,
    pub submitter: Entity,
    pub data: BTreeMap<String, String>,
}

impl TryFrom<HtmlEvent> for HtmlSubmit {
    type Error = ();
    fn try_from(event: HtmlEvent) -> Result<Self, Self::Error> {
        if event.kind != "submit" {
            return Err(());
        }
        Ok(Self {
            target: event.target,
            submitter: event.submitter.ok_or(())?,
            data: event.data,
        })
    }
}

/// Rust startup-system registration generated by `#[component_init]`.
pub struct ComponentInitRegistration {
    /// Adds the system to the application.
    pub register: fn(&mut App),
}

inventory::collect!(ComponentInitRegistration);

/// Rust update-system registration generated by `#[component_update]`.
pub struct ComponentUpdateRegistration {
    /// Adds the system to the application.
    pub register: fn(&mut App),
}

inventory::collect!(ComponentUpdateRegistration);

/// Rust event-handler registration generated by `#[html_fn]`.
pub struct HtmlHandlerRegistration {
    /// Name used in template event bindings.
    pub name: &'static str,
    /// Registers the handler as a Bevy system.
    pub register: fn(&mut World) -> SystemId<In<HtmlEvent>, ()>,
}

inventory::collect!(HtmlHandlerRegistration);

/// Installs Rust component startup systems and template event handlers.
#[derive(Debug, Default, Clone, Copy)]
pub struct TiltUiCodePlugin;

impl Plugin for TiltUiCodePlugin {
    fn build(&self, app: &mut App) {
        install(app);
    }
}

#[derive(bevy::ecs::resource::Resource, Default)]
struct HandlerSystems(HashMap<&'static str, SystemId<In<HtmlEvent>, ()>>);

#[derive(bevy::ecs::resource::Resource, Default)]
struct HandlerCursor(MessageCursor<HtmlEvent>);

pub(super) fn install(app: &mut App) {
    super::binding::install(app);
    for registration in inventory::iter::<ComponentInitRegistration> {
        (registration.register)(app);
    }
    for registration in inventory::iter::<ComponentUpdateRegistration> {
        (registration.register)(app);
    }
    app.add_message::<HtmlEvent>()
        .add_message::<FormSubmitted>()
        .init_resource::<HandlerCursor>()
        .add_systems(
            Update,
            (
                super::binding::refresh_shared_values,
                super::binding_runtime::apply_bindings,
            )
                .chain()
                .after(super::TiltUiComponentRuntimeSet::Instantiate),
        )
        .add_systems(
            Update,
            (forward_activations, forward_checked, forward_edited)
                .after(crate::control::TiltControlSystems::Selection),
        )
        .add_systems(
            Update,
            forward_submissions.after(crate::widgets::structure::form::process_form_activation),
        )
        .add_systems(
            Update,
            dispatch_html_events
                .after(forward_activations)
                .after(forward_checked)
                .after(forward_edited)
                .after(forward_submissions),
        );

    let mut systems = HandlerSystems::default();
    for registration in inventory::iter::<HtmlHandlerRegistration> {
        systems
            .0
            .insert(registration.name, (registration.register)(app.world_mut()));
    }
    app.insert_resource(systems);
}

fn handler_for(
    event: &str,
    static_attributes: Option<&StaticAttributes>,
    bindings: Option<&EventBindings>,
) -> Option<String> {
    let authored = format!("on{event}");
    let handler = bindings
        .and_then(|bindings| {
            bindings
                .bindings
                .iter()
                .find(|binding| binding.name == event || binding.name == authored)
                .map(|binding| binding.expression.clone())
        })
        .or_else(|| {
            static_attributes.and_then(|attributes| {
                attributes
                    .attributes
                    .iter()
                    .find(|attribute| attribute.name == authored)
                    .map(|attribute| attribute.value.clone())
            })
        });
    handler
        .map(|handler| {
            handler
                .trim()
                .strip_suffix("()")
                .unwrap_or(handler.trim())
                .trim()
                .to_owned()
        })
        .filter(|handler| !handler.is_empty())
}

fn forward_activations(
    mut source: MessageReader<ControlActivated>,
    elements: bevy::ecs::system::Query<(Option<&StaticAttributes>, Option<&EventBindings>)>,
    mut events: MessageWriter<HtmlEvent>,
) {
    for activation in source.read() {
        let Ok((attributes, bindings)) = elements.get(activation.entity) else {
            continue;
        };
        if let Some(handler) = handler_for("click", attributes, bindings) {
            events.write(HtmlEvent {
                target: activation.entity,
                kind: "click",
                value: None,
                submitter: None,
                data: BTreeMap::new(),
                handler,
            });
        }
    }
}

fn forward_checked(
    mut source: MessageReader<ControlCheckedChanged>,
    elements: bevy::ecs::system::Query<(Option<&StaticAttributes>, Option<&EventBindings>)>,
    mut events: MessageWriter<HtmlEvent>,
) {
    for change in source.read() {
        let Ok((attributes, bindings)) = elements.get(change.entity) else {
            continue;
        };
        if let Some(handler) = handler_for("change", attributes, bindings) {
            events.write(HtmlEvent {
                target: change.entity,
                kind: "change",
                value: Some(change.checked.to_string()),
                submitter: None,
                data: BTreeMap::new(),
                handler,
            });
        }
    }
}

fn forward_edited(
    mut source: MessageReader<EditableTextChanged>,
    elements: bevy::ecs::system::Query<(Option<&StaticAttributes>, Option<&EventBindings>)>,
    mut events: MessageWriter<HtmlEvent>,
) {
    for change in source.read() {
        let Ok((attributes, bindings)) = elements.get(change.entity) else {
            continue;
        };
        if let Some(handler) = handler_for("change", attributes, bindings) {
            events.write(HtmlEvent {
                target: change.entity,
                kind: "change",
                value: Some(change.value.clone()),
                submitter: None,
                data: BTreeMap::new(),
                handler,
            });
        }
    }
}

fn forward_submissions(
    mut source: MessageReader<FormSubmitted>,
    elements: bevy::ecs::system::Query<(Option<&StaticAttributes>, Option<&EventBindings>)>,
    mut events: MessageWriter<HtmlEvent>,
) {
    for submission in source.read() {
        let Ok((attributes, bindings)) = elements.get(submission.form) else {
            continue;
        };
        let handler =
            handler_for("submit", attributes, bindings).or_else(|| submission.action.clone());
        if let Some(handler) = handler {
            events.write(HtmlEvent {
                target: submission.form,
                kind: "submit",
                value: None,
                submitter: Some(submission.submitter),
                data: submission.data.clone(),
                handler,
            });
        }
    }
}

fn dispatch_html_events(world: &mut World) {
    let events = world.resource_scope(
        |world, mut cursor: bevy::ecs::change_detection::Mut<HandlerCursor>| {
            cursor
                .0
                .read(world.resource::<Messages<HtmlEvent>>())
                .cloned()
                .collect::<Vec<_>>()
        },
    );
    for event in events {
        let system = world
            .resource::<HandlerSystems>()
            .0
            .get(event.handler.as_str())
            .copied();
        if let Some(system) = system {
            let _ = world.run_system_with(system, event);
        }
    }
}
