use std::{
    env, fs,
    path::{Path, PathBuf},
};

use tilt_ui_core::ComponentKind;
use tilt_ui_html::parse_document;

use crate::UiSourceRoot;

use super::{ComponentBuildError, ComponentManifest, DiscoveredComponent, discover_components};

const GENERATED_MANIFEST_FILE: &str = "tilt_ui_components.rs";

/// Discovers components from Cargo's consumer project and writes their manifest.
pub fn build() -> Result<(), ComponentBuildError> {
    let source_root = UiSourceRoot::from_cargo_manifest_dir()?;
    build_from(&source_root)
}

/// Generates a manifest from a caller-selected source root.
pub fn build_from(source_root: &UiSourceRoot) -> Result<(), ComponentBuildError> {
    source_root.ensure()?;
    let document_styles = validate_index_document(source_root)?;
    let output_directory =
        env::var_os("OUT_DIR").ok_or(ComponentBuildError::MissingOutDirectory)?;
    let manifest = generate_components(source_root, PathBuf::from(output_directory))?;

    for directive in cargo_rebuild_directives(source_root.path(), &manifest.components) {
        println!("{directive}");
    }
    println!(
        "cargo:rerun-if-changed={}",
        source_root.path().join("index.html").display()
    );
    for path in document_styles {
        println!("cargo:rerun-if-changed={}", path.display());
    }
    Ok(())
}

fn validate_index_document(
    source_root: &UiSourceRoot,
) -> Result<Vec<PathBuf>, ComponentBuildError> {
    let path = source_root.path().join("index.html");
    let source = fs::read_to_string(&path).map_err(|error| {
        if error.kind() == std::io::ErrorKind::NotFound {
            ComponentBuildError::IndexMissing { path: path.clone() }
        } else {
            ComponentBuildError::InvalidIndex {
                path: path.clone(),
                reason: error.to_string(),
            }
        }
    })?;
    let document = parse_document(&source).map_err(|error| ComponentBuildError::InvalidIndex {
        path: path.clone(),
        reason: error.to_string(),
    })?;
    let canonical_root = fs::canonicalize(source_root.path()).map_err(|error| {
        ComponentBuildError::InvalidIndex {
            path: path.clone(),
            reason: error.to_string(),
        }
    })?;
    let mut styles = Vec::new();
    for href in document.head.stylesheet_links {
        let relative = href.trim_start_matches('/');
        if relative.is_empty() || !relative.ends_with(".css") || href.contains(['?', '#', ':']) {
            return Err(ComponentBuildError::InvalidIndexStylesheet {
                path: path.clone(),
                href,
                reason: "expected a local .css path".into(),
            });
        }
        let style = fs::canonicalize(source_root.path().join(relative)).map_err(|error| {
            ComponentBuildError::InvalidIndexStylesheet {
                path: path.clone(),
                href: href.clone(),
                reason: error.to_string(),
            }
        })?;
        if !style.starts_with(&canonical_root) {
            return Err(ComponentBuildError::InvalidIndexStylesheet {
                path: path.clone(),
                href,
                reason: "path escapes src-ui".into(),
            });
        }
        styles.push(style);
    }
    Ok(styles)
}

/// Discovers components and writes their generated manifest into an output directory.
pub fn generate_components(
    source_root: &UiSourceRoot,
    output_directory: impl AsRef<Path>,
) -> Result<ComponentManifest, ComponentBuildError> {
    let components = discover_components(source_root)?;
    let generated_path = output_directory.as_ref().join(GENERATED_MANIFEST_FILE);
    let generated = generate_manifest(&components);
    fs::write(&generated_path, generated).map_err(|source| {
        ComponentBuildError::WriteGeneratedManifest {
            path: generated_path.clone(),
            source,
        }
    })?;

    Ok(ComponentManifest {
        components,
        generated_path,
    })
}

/// Generates module wiring and static metadata for validated components.
pub fn generate_manifest(components: &[DiscoveredComponent]) -> String {
    let mut output =
        String::from("// This file is generated by tilt-ui-build.\n// Do not edit manually.\n\n");

    for component in components {
        output.push_str(&format!(
            "#[doc = \"Original TiltUI component logic module.\"]\n#[path = {}]\npub mod {};\n\n",
            rust_string(&component.logic_path.to_string_lossy()),
            component.module_identifier
        ));
    }

    output.push_str("/// Static metadata for every component discovered during this build.\npub static TILT_UI_COMPONENTS: &[ComponentMetadata] = &[\n");
    for component in components {
        let kind = match component.kind {
            ComponentKind::Page => "Page",
            ComponentKind::Component => "Component",
        };
        let paths = component
            .stylesheet_asset_paths
            .iter()
            .map(|path| rust_string(path))
            .collect::<Vec<_>>()
            .join(", ");
        output.push_str(&format!(
            "    ComponentMetadata {{ id: ComponentId({}), name: {}, kind: ComponentKind::{kind}, template_asset_path: {}, stylesheet_asset_path: {}, stylesheet_asset_paths: &[{}] }},\n",
            component.id.0,
            rust_string(&component.name),
            rust_string(&component.template_asset_path),
            rust_string(&component.stylesheet_asset_path),
            paths,
        ));
    }
    output.push_str("];\n\n");
    output.push_str(
        "/// Returns static metadata for every component discovered during this build.\npub fn tilt_ui_components() -> &'static [ComponentMetadata] {\n    TILT_UI_COMPONENTS\n}\n\n",
    );
    output.push_str(
        "/// Looks up a generated component identifier by convention-derived name.\npub fn tilt_ui_component_id(name: &str) -> Option<ComponentId> {\n    match name {\n",
    );
    for component in components {
        output.push_str(&format!(
            "        {} => Some(ComponentId({})),\n",
            rust_string(&component.name),
            component.id.0
        ));
    }
    output.push_str("        _ => None,\n    }\n}\n\n");
    output.push_str("/// Looks up static component metadata by generated identifier.\npub fn tilt_ui_component_metadata(id: ComponentId) -> Option<&'static ComponentMetadata> {\n    match id {\n");
    for component in components {
        output.push_str(&format!(
            "        ComponentId({}) => Some(&TILT_UI_COMPONENTS[{}]),\n",
            component.id.0, component.id.0
        ));
    }
    output.push_str("        _ => None,\n    }\n}\n");
    output.push_str("\n/// Returns the generated static catalog consumed by TiltUI's component runtime.\npub fn tilt_ui_component_catalog() -> ComponentCatalog {\n    ComponentCatalog::new(tilt_ui_components(), tilt_ui_component_id, tilt_ui_component_metadata)\n}\n");
    output
}

/// Returns Cargo directives covering the source root and discovered triplet files.
pub fn cargo_rebuild_directives(
    source_root: &Path,
    components: &[DiscoveredComponent],
) -> Vec<String> {
    let mut directives = vec![format!("cargo:rerun-if-changed={}", source_root.display())];
    for component in components {
        for path in [&component.logic_path, &component.template_path] {
            directives.push(format!("cargo:rerun-if-changed={}", path.display()));
        }
        for path in &component.stylesheet_paths {
            directives.push(format!("cargo:rerun-if-changed={}", path.display()));
        }
    }
    directives
}

fn rust_string(value: &str) -> String {
    format!("{value:?}")
}

#[cfg(test)]
mod document_tests {
    use std::{fs, path::PathBuf, process};

    use super::validate_index_document;
    use crate::{ComponentBuildError, UiSourceRoot};

    struct Project(PathBuf);

    impl Project {
        fn new() -> Self {
            let path = std::env::temp_dir().join(format!(
                "tilt-ui-index-test-{}-{}",
                process::id(),
                std::time::SystemTime::now()
                    .duration_since(std::time::UNIX_EPOCH)
                    .unwrap()
                    .as_nanos()
            ));
            fs::create_dir(&path).unwrap();
            Self(path)
        }

        fn root(&self) -> UiSourceRoot {
            UiSourceRoot::new(&self.0)
        }
    }

    impl Drop for Project {
        fn drop(&mut self) {
            fs::remove_dir_all(&self.0).unwrap();
        }
    }

    #[test]
    fn index_is_required_and_local_links_are_checked() {
        let project = Project::new();
        let root = project.root();
        assert!(matches!(
            validate_index_document(&root),
            Err(ComponentBuildError::IndexMissing { .. })
        ));
        fs::write(
            project.0.join("index.html"),
            "<!doctype html><html><head><link rel=stylesheet href='styles/site.css'></head><body><p>Hi</body></html>",
        )
        .unwrap();
        assert!(matches!(
            validate_index_document(&root),
            Err(ComponentBuildError::InvalidIndexStylesheet { .. })
        ));
        fs::create_dir(project.0.join("styles")).unwrap();
        fs::write(project.0.join("styles/site.css"), "p { color: red; }").unwrap();
        assert_eq!(validate_index_document(&root).unwrap().len(), 1);
        fs::write(
            project.0.join("index.html"),
            "<html><head><link rel=stylesheet href='../escape.css'></head><body></body></html>",
        )
        .unwrap();
        assert!(matches!(
            validate_index_document(&root),
            Err(ComponentBuildError::InvalidIndexStylesheet { .. })
        ));
    }
}
