[workspace]
resolver = "2"

members = [
    "crates/*",
    "examples/*",
]

default-members = [
    "crates/tilt-ui",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
repository = "https://github.com/exepta/tilt-ui"

[workspace.dependencies]
# TiltUI internal crates
tilt-ui = { path = "crates/tilt-ui", version = "=0.1.0" }
tilt-ui-core = { path = "crates/tilt-ui-core", version = "=0.1.0" }
tilt-ui-html = { path = "crates/tilt-ui-html", version = "=0.1.0" }
tilt-ui-css = { path = "crates/tilt-ui-css", version = "=0.1.0" }
tilt-ui-runtime = { path = "crates/tilt-ui-runtime", version = "=0.1.0" }
tilt-ui-icons = { path = "crates/tilt-ui-icons", version = "=0.1.0" }
tilt-ui-macros = { path = "crates/tilt-ui-macros", version = "=0.1.0" }
tilt-ui-build = { path = "crates/tilt-ui-build", version = "=0.1.0" }

# Bevy
bevy = { version = "0.19", default-features = false }

# HTML parsing
quick-xml = "0.42"

# CSS parsing
cssparser = "0.37"
selectors = "0.40"
precomputed-hash = "0.1"

# Utilities
thiserror = "2"
smallvec = "1"
inventory = "0.3"
parley = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.dev.package."*"]
opt-level = 3
