[package]
name = "tilt-ui-example-icons-catalog"
version = "0.0.0"
edition.workspace = true
publish = false

[[bin]]
name = "tilt-ui-example-icons-catalog"
path = "src/main.rs"

[dependencies]
bevy = { workspace = true, features = [
    "bevy_core_pipeline",
    "bevy_ui_render",
    "bevy_winit",
    "default_font",
    "png",
    "wayland",
    "x11",
] }
tilt-ui = { workspace = true, features = ["tilt-icons"] }

[build-dependencies]
tilt-ui-build.workspace = true

[dev-dependencies]
tilt-ui-html.workspace = true
