[package]
name = "tilt-ui-macros"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Procedural macros for TiltUI"
readme = "README.md"

[lib]
proc-macro = true
path = "src/lib.rs"

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
