use crate::{
    AlignItems, AlignSelf, AnimationDirection, AnimationName, AnimationSpec, BorderRadius,
    CssColor, CssGradient, CssOverflow, CssTime, CssTransform, Display, Edges, FlexDirection,
    FlexWrap, FontFamily, FontWeight, IterationCount, JustifyContent, Length, Position, TextAlign,
    TimingFunction, TransitionProperty, TransitionSpec,
};

/// Stores the resolved typed CSS values that apply to one TiltUI runtime node.
///
/// `None` represents the CSS initial value for non-inherited properties, or an
/// inherited value that has not been resolved yet for inherited properties.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct ComputedStyle {
    pub display: Option<Display>,
    pub overflow_x: Option<CssOverflow>,
    pub overflow_y: Option<CssOverflow>,
    pub position: Option<Position>,
    pub width: Option<Length>,
    pub height: Option<Length>,
    pub min_width: Option<Length>,
    pub min_height: Option<Length>,
    pub max_width: Option<Length>,
    pub max_height: Option<Length>,
    pub top: Option<Length>,
    pub right: Option<Length>,
    pub bottom: Option<Length>,
    pub left: Option<Length>,
    pub margin: Option<Edges<Length>>,
    pub padding: Option<Edges<Length>>,
    pub row_gap: Option<Length>,
    pub column_gap: Option<Length>,
    pub flex_direction: Option<FlexDirection>,
    pub flex_wrap: Option<FlexWrap>,
    pub justify_content: Option<JustifyContent>,
    pub align_items: Option<AlignItems>,
    pub align_self: Option<AlignSelf>,
    pub flex_grow: Option<f32>,
    pub flex_shrink: Option<f32>,
    pub background_color: Option<CssColor>,
    pub background_image: Option<CssGradient>,
    pub border_width: Option<Edges<Length>>,
    pub border_color: Option<CssColor>,
    pub border_radius: Option<BorderRadius>,
    pub color: Option<CssColor>,
    pub font_size: Option<Length>,
    pub font_family: Option<FontFamily>,
    pub font_weight: Option<FontWeight>,
    pub text_align: Option<TextAlign>,
    pub opacity: Option<f32>,
    pub transform: Option<CssTransform>,
    pub animation: Option<Vec<AnimationSpec>>,
    pub animation_name: Option<Vec<Option<AnimationName>>>,
    pub animation_duration: Option<Vec<CssTime>>,
    pub animation_delay: Option<Vec<CssTime>>,
    pub animation_timing_function: Option<Vec<TimingFunction>>,
    pub animation_iteration_count: Option<Vec<IterationCount>>,
    pub animation_direction: Option<Vec<AnimationDirection>>,
    pub transition: Option<Vec<TransitionSpec>>,
    pub transition_property: Option<Vec<TransitionProperty>>,
    pub transition_duration: Option<Vec<CssTime>>,
    pub transition_delay: Option<Vec<CssTime>>,
    pub transition_timing_function: Option<Vec<TimingFunction>>,
}
