use crate::{
    AlignItems, AlignSelf, AnimatedEffect, AnimationDirection, AnimationName, AnimationSpec,
    BackgroundAttachment, BackgroundEffect, BackgroundPosition, BackgroundSize, BorderRadius,
    BorderStyle, BoxSizing, CssBackgroundImage, CssBoxShadow, CssColor, CssCursor, CssLineHeight,
    CssOverflow, CssTextShadow, CssTime, CssTransform, Display, Edges, EffectQuality,
    FlexDirection, FlexWrap, FontFamily, FontWeight, GridAutoFlow, GridPlacement, GridTrackGroup,
    GridTrackSize, IterationCount, JustifyContent, Length, PointerEvents, Position, TextAlign,
    TextTransform, TextWrap, TimingFunction, TransitionProperty, TransitionSpec,
};

/// Stores the resolved typed CSS values that apply to one TiltUI runtime node.
///
/// `None` represents the CSS initial value for non-inherited properties, or an
/// inherited value that has not been resolved yet for inherited properties.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct ComputedStyle {
    pub display: Option<Display>,
    pub box_sizing: Option<BoxSizing>,
    pub pointer_events: Option<PointerEvents>,
    pub cursor: Option<CssCursor>,
    pub z_index: Option<i32>,
    pub scroll_width: Option<f32>,
    pub overflow_x: Option<CssOverflow>,
    pub overflow_y: Option<CssOverflow>,
    pub position: Option<Position>,
    pub width: Option<Length>,
    pub height: Option<Length>,
    pub min_width: Option<Length>,
    pub min_height: Option<Length>,
    pub max_width: Option<Length>,
    pub max_height: Option<Length>,
    pub top: Option<Length>,
    pub right: Option<Length>,
    pub bottom: Option<Length>,
    pub left: Option<Length>,
    pub margin: Option<Edges<Length>>,
    pub padding: Option<Edges<Length>>,
    pub row_gap: Option<Length>,
    pub column_gap: Option<Length>,
    pub flex_direction: Option<FlexDirection>,
    pub flex_wrap: Option<FlexWrap>,
    pub justify_content: Option<JustifyContent>,
    pub align_items: Option<AlignItems>,
    pub align_self: Option<AlignSelf>,
    pub flex_grow: Option<f32>,
    pub flex_shrink: Option<f32>,
    pub flex_basis: Option<Length>,
    pub grid_template_rows: Option<Vec<GridTrackGroup>>,
    pub grid_template_columns: Option<Vec<GridTrackGroup>>,
    pub grid_auto_rows: Option<Vec<GridTrackSize>>,
    pub grid_auto_columns: Option<Vec<GridTrackSize>>,
    pub grid_auto_flow: Option<GridAutoFlow>,
    pub grid_row: Option<GridPlacement>,
    pub grid_column: Option<GridPlacement>,
    pub background_color: Option<CssColor>,
    pub background_image: Option<CssBackgroundImage>,
    pub background_size: Option<BackgroundSize>,
    pub background_position: Option<BackgroundPosition>,
    pub background_attachment: Option<BackgroundAttachment>,
    pub background_filter: Option<Vec<BackgroundEffect>>,
    pub backdrop_filter: Option<Vec<BackgroundEffect>>,
    pub animated_effects: Option<Vec<AnimatedEffect>>,
    pub effect_quality: Option<EffectQuality>,
    pub border_width: Option<Edges<Length>>,
    pub border_color: Option<CssColor>,
    pub border_color_edges: Option<Edges<CssColor>>,
    pub border_style: Option<Edges<BorderStyle>>,
    pub border_brush_strength: Option<f32>,
    pub border_radius: Option<BorderRadius>,
    pub box_shadow: Option<Vec<CssBoxShadow>>,
    pub text_shadow: Option<CssTextShadow>,
    pub outline_width: Option<Length>,
    pub outline_color: Option<CssColor>,
    pub outline_offset: Option<Length>,
    pub color: Option<CssColor>,
    pub font_size: Option<Length>,
    pub line_height: Option<CssLineHeight>,
    pub font_family: Option<FontFamily>,
    pub font_weight: Option<FontWeight>,
    pub text_align: Option<TextAlign>,
    pub text_wrap: Option<TextWrap>,
    pub text_transform: Option<TextTransform>,
    pub opacity: Option<f32>,
    pub transform: Option<CssTransform>,
    pub animation: Option<Vec<AnimationSpec>>,
    pub animation_name: Option<Vec<Option<AnimationName>>>,
    pub animation_duration: Option<Vec<CssTime>>,
    pub animation_delay: Option<Vec<CssTime>>,
    pub animation_timing_function: Option<Vec<TimingFunction>>,
    pub animation_iteration_count: Option<Vec<IterationCount>>,
    pub animation_direction: Option<Vec<AnimationDirection>>,
    pub transition: Option<Vec<TransitionSpec>>,
    pub transition_property: Option<Vec<TransitionProperty>>,
    pub transition_duration: Option<Vec<CssTime>>,
    pub transition_delay: Option<Vec<CssTime>>,
    pub transition_timing_function: Option<Vec<TimingFunction>>,
}
