//! Internal 24×24 SVG geometry, grouped by icon family.

mod home;
pub(crate) use home::*;
mod settings;
pub(crate) use settings::*;
mod user;
pub(crate) use user::*;
mod menu;
pub(crate) use menu::*;
mod close;
pub(crate) use close::*;
mod briefcase;
pub(crate) use briefcase::*;
mod general;
pub(crate) use general::*;
mod navigation;
pub(crate) use navigation::*;
mod devices;
pub(crate) use devices::*;
mod actions;
pub(crate) use actions::*;
mod files;
pub(crate) use files::*;
mod commerce;
pub(crate) use commerce::*;
mod communication;
pub(crate) use communication::*;
mod media;
pub(crate) use media::*;
mod editor;
pub(crate) use editor::*;
mod weather;
pub(crate) use weather::*;
mod data;
pub(crate) use data::*;
mod security;
pub(crate) use security::*;
mod travel;
pub(crate) use travel::*;
mod productivity;
pub(crate) use productivity::*;
mod development;
pub(crate) use development::*;
mod health;
pub(crate) use health::*;
mod food;
pub(crate) use food::*;
mod sports;
pub(crate) use sports::*;
mod social;
pub(crate) use social::*;
mod interface;
pub(crate) use interface::*;
mod finance;
pub(crate) use finance::*;
mod science;
pub(crate) use science::*;
mod misc;
pub(crate) use misc::*;
mod bevy;
pub(crate) use bevy::*;
mod animated;
pub(crate) use animated::*;
mod animals;
pub(crate) use animals::*;
mod wildlife;
pub(crate) use wildlife::*;
mod gaming;
pub(crate) use gaming::*;
mod boardgames;
pub(crate) use boardgames::*;
mod learning;
pub(crate) use learning::*;
mod household;
pub(crate) use household::*;
mod creative;
pub(crate) use creative::*;
mod mobility;
pub(crate) use mobility::*;
mod apps_gaming;
pub(crate) use apps_gaming::*;
mod apps_social;
pub(crate) use apps_social::*;
mod apps_tools;
pub(crate) use apps_tools::*;
mod nature_flora;
pub(crate) use nature_flora::*;
mod nature_sky;
pub(crate) use nature_sky::*;
mod nature_landscape;
pub(crate) use nature_landscape::*;
mod animals_more;
pub(crate) use animals_more::*;
mod animals_wildlife;
pub(crate) use animals_wildlife::*;
mod apps_browsers;
pub(crate) use apps_browsers::*;
mod apps_developer;
pub(crate) use apps_developer::*;
mod apps_community;
pub(crate) use apps_community::*;
mod utils_workflow;
pub(crate) use utils_workflow::*;
mod utils_tools;
pub(crate) use utils_tools::*;
