//! Public facade for TiltUI's core model and Bevy runtime integration.

pub use bevy;
pub use inventory;
pub use serde;
pub use serde_json;
pub use tilt_ui_core::*;
pub use tilt_ui_runtime::{
    DEFAULT_TILT_UI_ASSET_PATH, TILT_UI_ASSET_SOURCE, TiltUiAssetSourcePlugin, TiltUiAssetsPlugin,
};

/// Re-exports procedural macros implemented by `tilt-ui-macros`.
#[allow(unused_imports)]
pub use tilt_ui_macros::*;

#[cfg(feature = "component")]
mod plugin;
#[cfg(feature = "component")]
pub use plugin::{TiltUiCameraMode, TiltUiPlugin};

/// Common public TiltUI runtime imports.
#[cfg(feature = "component")]
pub mod prelude;

/// Includes the component manifest generated by `tilt-ui-build`.
///
/// The generated manifest connects original `.component.rs` files to the
/// consumer crate through `#[path]` module declarations and exposes static
/// component metadata. IDE tooling must run Cargo build scripts for the
/// generated manifest to be visible.
#[macro_export]
macro_rules! include_components {
    () => {
        #[doc(hidden)]
        pub mod __tilt_ui_generated_components {
            use $crate::{ComponentCatalog, ComponentId, ComponentKind, ComponentMetadata};

            include!(concat!(env!("OUT_DIR"), "/tilt_ui_components.rs"));
        }

        pub use __tilt_ui_generated_components::*;
    };
}

#[cfg(feature = "css")]
pub use tilt_ui_runtime::{
    UiStyleSheetAsset, UiStyleSheetAssetLoader, UiStyleSheetAssetLoaderError,
};
#[cfg(feature = "html")]
pub use tilt_ui_runtime::{UiTemplateAsset, UiTemplateAssetLoader, UiTemplateAssetLoaderError};

#[cfg(feature = "component")]
pub use tilt_ui_runtime::component::ComponentUpdateRegistration;

#[cfg(feature = "component")]
pub use tilt_ui_runtime::{
    BeuStore, CascadedStyle, ComponentAssetHandles, ComponentAssetStore, ComponentCatalog,
    ComponentInitRegistration, ComponentInstance, ComponentInstantiationError, ComponentRoot,
    ComponentStyleOwner, ContextMenu, ControlActivated, ControlChecked, ControlCheckedChanged,
    ControlPart, ControlPartKind, ControlTabIndex, DialogClosed, DialogConfig, DialogKind,
    DialogLayout, DialogRenderer, DialogResult, DialogSpawned, DialogState, EditableText,
    EditableTextChanged, EditableTextCommitted, EditableTextOptions, ElementClasses, ElementId,
    ElementState, EventBinding, EventBindings, FailedComponentInstantiation, FieldSetSelection,
    FileInputOptions, FileInputSelected, FileInputSelection, FormButton, FormSettings,
    FormSubmitted, FormValidationFailed, HtmlChange, HtmlClick, HtmlEvent, HtmlHandlerRegistration,
    HtmlSubmit, LoadedComponentAssets, NumericParts, NumericRange, NumericValueChanged,
    PendingComponent, PropertyBinding, PropertyBindings, RangeOrientation, RouteTarget, Router,
    Routes, RoutesRegistration, RuntimeComputedStyle, SelectableStaticText,
    SharedValueRegistration, ShowDialog, SliderChanged, SliderCommitted, SliderSettings,
    StaticAttribute, StaticAttributes, TableCellInfo, TableInfo, TableSection, TemplateNodeRef,
    TiltButton, TiltCheckbox, TiltControl, TiltElement, TiltRadioButton, TiltSwitchButton,
    TiltText, TiltToggleButton, TiltUiCodePlugin, TiltUiComponentRuntimePlugin,
    TiltUiComponentRuntimeSet, TiltUiControlRuntimePlugin, TiltUiRouterPlugin,
    TiltUiStyleRuntimePlugin, UiBindingStore, UiMotionSettings, UiSharedValues,
    UiStoreRegistration, WidgetLayoutOverride, close_dialog, instantiate_component, open_dialog,
    reset_default_theme, set_control_checked, set_default_theme_css, set_editable_readonly,
    set_editable_text, set_numeric_value, set_progress_value, set_slider_value, set_slider_values,
    set_text_area_size, spawn_component, spawn_dialog,
};
