//! Public facade for TiltUI's core model and Bevy runtime integration.

pub use bevy;
pub use inventory;
pub use serde;
pub use serde_json;
pub use tilt_ui_core::*;
#[cfg(feature = "tilt-icons")]
pub use tilt_ui_icons::{self, Icon, IconSize};
#[cfg(feature = "css")]
pub use tilt_ui_runtime::tilt_ui_css;
pub use tilt_ui_runtime::{
    DEFAULT_TILT_UI_ASSET_PATH, TILT_UI_ASSET_SOURCE, TiltUiAssetSourcePlugin, TiltUiAssetsPlugin,
    UiRuntimeConfiguration,
};
#[cfg(feature = "tilt-icons")]
pub use tilt_ui_runtime::{icon_image, set_icon_size};

#[cfg(feature = "fluent")]
pub use tilt_ui_runtime::{
    UiFluentArgs, UiFluentAsset, UiFluentAssetLoader, UiFluentConfig, UiFluentError,
    UiFluentPlugin, UiFluentValue, UiLocalization,
};

/// Re-exports procedural macros implemented by `tilt-ui-macros`.
#[allow(unused_imports)]
pub use tilt_ui_macros::*;

#[cfg(all(feature = "component", not(target_arch = "wasm32")))]
mod discovery;
#[cfg(feature = "component")]
mod plugin;
#[cfg(all(feature = "component", not(target_arch = "wasm32")))]
pub use discovery::refresh_ui_directories;
#[cfg(feature = "component")]
pub use plugin::{TiltUiCameraMode, TiltUiPlugin, UiCameraConfiguration, UiFrameRate};

/// Common public TiltUI runtime imports.
#[cfg(feature = "component")]
pub mod prelude;

/// Includes the component manifest generated by `tilt-ui-build`.
///
/// The generated manifest connects original `.component.rs` files to the
/// consumer crate through `#[path]` module declarations and exposes static
/// component metadata. IDE tooling must run Cargo build scripts for the
/// generated manifest to be visible.
#[macro_export]
macro_rules! include_components {
    () => {
        #[doc(hidden)]
        pub mod __tilt_ui_generated_components {
            use $crate::{ComponentCatalog, ComponentId, ComponentKind, ComponentMetadata};

            include!(concat!(env!("OUT_DIR"), "/tilt_ui_components.rs"));
        }

        pub use __tilt_ui_generated_components::*;
    };
}

#[cfg(feature = "css")]
pub use tilt_ui_runtime::{
    UiStyleSheetAsset, UiStyleSheetAssetLoader, UiStyleSheetAssetLoaderError,
};

/// Eagerly creates a route component and retains its state across navigation.
#[cfg(feature = "component")]
#[macro_export]
macro_rules! load {
    ($component:expr) => {
        $crate::RouteComponent::load($component)
    };
}

/// Creates a route component on first visit and retains its state afterward.
#[cfg(feature = "component")]
#[macro_export]
macro_rules! lazy {
    ($component:expr) => {
        $crate::RouteComponent::lazy($component)
    };
}
#[cfg(feature = "html")]
pub use tilt_ui_runtime::{UiTemplateAsset, UiTemplateAssetLoader, UiTemplateAssetLoaderError};

#[cfg(feature = "component")]
pub use tilt_ui_runtime::component::ComponentUpdateRegistration;

#[cfg(feature = "component")]
pub use tilt_ui_runtime::{
    CascadedStyle, ChoiceBoxParts, ColorPickerChanged, ComponentAssetHandles, ComponentAssetStore,
    ComponentCatalog, ComponentElementIds, ComponentInitRegistration, ComponentInstance,
    ComponentInstantiationError, ComponentRoot, ComponentStyleOwner, ContextMenu, ControlActivated,
    ControlChecked, ControlCheckedChanged, ControlPart, ControlPartKind, ControlTabIndex,
    DatePickerChanged, DatePickerRangeChanged, DatePickerState, DialogClosed, DialogConfig,
    DialogKind, DialogLayout, DialogRenderer, DialogResult, DialogSpawned, DialogState,
    EditableText, EditableTextChanged, EditableTextCommitted, EditableTextOptions, ElementClasses,
    ElementId, ElementState, EventBinding, EventBindings, FailedComponentInstantiation,
    FieldSetSelection, FileInputOptions, FileInputSelected, FileInputSelection, FormButton,
    FormData, FormFile, FormSettings, FormSubmitted, FormValidationFailed, FormValue, HtmlChange,
    HtmlClick, HtmlEvent, HtmlExpressionMethod, HtmlHandlerRegistration, HtmlMethodRegistration,
    HtmlSubmit, ImageMetadata, ImagePreviewInput, InnerContentError, IsoDate,
    LoadedComponentAssets, NumericParts, NumericRange, NumericValueChanged, OptionData,
    OptionSelectionChanged, PendingComponent, PropertyBinding, PropertyBindings,
    ProviderChildPolicy, ProviderContext, ProviderEffect, ProviderRules, ProviderScope,
    RangeOrientation, RouteComponent, RouteLifetime, RouteTarget, Router, Routes,
    RoutesRegistration, RuntimeComputedStyle, SelectableStaticText, SharedValueRegistration,
    ShowDialog, ShowToast, SliderChanged, SliderCommitted, SliderSettings, StaticAttribute,
    StaticAttributes, TableCellInfo, TableInfo, TableSection, TemplateNodeRef, ThemeProvider,
    TiltButton, TiltCheckbox, TiltControl, TiltElement, TiltRadioButton, TiltSwitchButton,
    TiltText, TiltToggleButton, TiltUiCodePlugin, TiltUiComponentRuntimePlugin,
    TiltUiComponentRuntimeSet, TiltUiControlRuntimePlugin, TiltUiRouterPlugin,
    TiltUiStyleRuntimePlugin, ToastCloseReason, ToastClosed, ToastConfig, ToastKind,
    ToastPlacement, ToastSpawned, ToastStackSettings, ToastState, UiBindingStore, UiCursor,
    UiDocumentInfo, UiDocumentState, UiErrorCode, UiExpressionMethods, UiLoadState,
    UiMotionSettings, UiProvider, UiProviderAppExt, UiProviderRegistry, UiSharedValues, UiState,
    UiStateError, UiStateEvent, UiStateRuntimeSet, UiStateTarget, UiStore, UiStoreRegistration,
    UiThemeAppExt, UiThemes, WidgetLayoutOverride, close_dialog, close_toast,
    instantiate_component, normalize_path, open_dialog, register_ui_theme, remove_ui_theme,
    reset_default_theme, set_color_value, set_control_checked, set_date_picker_open,
    set_date_range, set_date_value, set_default_theme_css, set_editable_readonly,
    set_editable_text, set_image_source, set_inner_bindings, set_inner_html, set_inner_text,
    set_numeric_value, set_option_selected, set_progress_value, set_slider_value,
    set_slider_values, set_text_area_size, set_ui_cursor, show_toast, spawn_component,
    spawn_dialog, spawn_toast, switch_ui_theme,
};
